
#define TIMER0_MODE		TIMER0_PWM_FAST_MODE

#define TIMER0_PRESCALER	TIMER0_1024_PRESCALER

#define TIMER0_PRELOAD      212

#define OC0_PIN_MODE		OC0_PIN_DISCONNECTED

#define TIMER0_CTC			156

#define TIMER2_MODE		TIMER2_PWM_FAST_MODE

#define TIMER2_PRESCALER	TIMER2_1024_PRESCALER

#define TIMER2_PRELOAD      212

#define OC2_PIN_MODE		OC2_PIN_DISCONNECTED

#define TIMER2_CTC			156
